const data = {
  products: [
    {
      name: 'Race Car',
      slug: 'race-car',
      category: 'Art Work',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      author: 'vincy',
      rating: 3.5,
      numReviews: 10,
      description: 'High quality images',
    },
    {
      name: 'Montel ',
      slug: 'montel',
      category: 'Art Work',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 11,
      author: 'JjPp',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality images',
    },
    {
      name: 'Skulls',
      slug: 'skulls',
      category: 'Art Work',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 12,
      author: 'John',
      rating: 3.5,
      numReviews: 10,
      description: 'High quality images',
    },
    {
      name: 'DJ Wolf ',
      slug: 'dj-wolf',
      category: 'Art Work',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 13,
      author: 'JjPp',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality images',
    },
    {
      name: 'Motercycle Life',
      slug: 'motercycle-life',
      category: 'Art Work',
      image: '/images/p5.jpg',
      price: 130,
      countInStock: 14,
      author: 'Jusstin',
      rating: 2.5,
      numReviews: 15,
      description: 'High quality images',
    },
    {
      name: 'Dodge challanger',
      slug: 'dodge-challanger',
      category: 'Art Work',
      image: '/images/p6.jpg',
      price: 150,
      countInStock: 15,
      author: 'Justin',
      rating: 4.5,
      numReviews: 20,
      description: 'High quality images',
    },
  ],
};
export default data;
